[test.unit_square]
source_file = "PFAD ZUR DATEI"
test_method = "file comparison"

[file_comparison.parameters]
comparison_file = "PFAD ZUR VERGLEICHSDATEI"
preprocessor = "lines" # compare two files line by line
# Apply a regular expression to find the node-value in each line and
# convert it to a float.
preprocessor_params = {processing_pipeline = ["regex: r'\d+\ (?P<Result>\d+\.\d+)'", "float"]}
# we compare the two numbers via their relative error
verifier = "relative error"
verifier_params = {max_error = 1e-9}
