source_file = "/home/stefan/GitHub/Testing/examples/test_input.txt"
setup = "echo test"

[file_comparison.parameters]
comparison_file = "/home/stefan/GitHub/Testing/examples/test_comparison.txt"
# compare two files line by line
source_preprocessor = "lines"
comparison_preprocessor = "lines"
# Apply a regular expression to find the node-value in each line and
# convert it to a float.
source_preprocessor_params = {processing_pipeline = ['''lambda x: __import__("re").match(r"\d+\ (?P<Result>\d+\.\d+)", x).group("Result")''', "float"]}
comparison_preprocessor_params = {processing_pipeline = ['''lambda x: __import__("re").match(r"\d+\ (?P<Result>\d+\.\d+)", x).group("Result")''', "float"]}
# we compare the two numbers via their relative error
verifier = "relative_error"
verifier_params = {max_error = 1e-6}
